OSC 4;$index;$spec ST|BEL will -set- a colour, but if $spec is the
literal string questionmark, it will query it.
echo -e "\e]4;0;?\a" => terminal replies with \e]4;0;rgb:0000/0000/0000^G

reset xterm to use the default colors:
  \033]104\007

=head1 COLORS

=head2 Setting colors

    \e]4;$index;rgb:$r/$g/$b\e\\

Note that, given the literal questionmark character in place of the rgb
specification, it'll instead perform a query, see L</Getting colors>.

=head3 GNU Screen, Tmux

For GNU Screen and Tmux (who pretends to be Screen), the sequence must be
prefixed with C<\eP> and suffixed with an additional B<BEL>, C<\a>:

    \eP\e]4;$index:$r/$g/$b\a\e\\

=head2 Getting colors

  \e]4;$index;?\a

Returns the rgb values of index color $index. You need to talk directly to the
pty to perform this operation.

=head2 Resetting colors

Resets B<all> Xterm color mappings to their defaults:

    \e]104\007

=head1 CURSOR

=head2 Cursor position

Save cursor position:

    \e[s

Go back to the saved cursor position:

    \e[u

Erase everything from the cursor to EOL:

    \e[K

=cut
